name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: '28.1'

    - name: Install package-lint
      run: |
        emacs --batch --eval "(require 'package)" \
              --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" \
              --eval "(package-initialize)" \
              --eval "(package-refresh-contents)" \
              --eval "(package-install 'package-lint)"

    - name: Lint
      run: |
        emacs --batch -l package-lint.el \
              --eval "(setq package-lint-main-file \"ellm.el\")" \
              -f package-lint-batch-and-exit ellm.el ellm-tests.el