name: MELPA

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: '28.1'

    - name: Clone MELPA
      run: |
        git clone https://github.com/melpa/melpa.git ~/melpa

    - name: Create MELPA recipe
      run: |
        mkdir -p ~/melpa/recipes
        echo '(ellm :fetcher github :repo "yourusername/ellm.el")' > ~/melpa/recipes/ellm

    - name: Build package
      run: |
        cd ~/melpa
        make recipes/ellm