name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '27.1'
          - '28.1'
          - '29.1'
          - 'snapshot'
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install dependencies
      run: |
        # No external dependencies needed - ellm uses built-in packages only

    - name: Check for byte-compilation warnings
      run: |
        emacs -Q --batch \
          --eval "(setq byte-compile-error-on-warn t)" \
          -f batch-byte-compile ellm.el
      
    - name: Check package loads correctly
      run: |
        emacs -Q --batch \
          --eval "(add-to-list 'load-path (expand-file-name \".\"))" \
          --eval "(require 'ellm)" \
          --eval "(message \"✓ Package loaded successfully\")"
          
    - name: Run ERT tests
      run: |
        emacs -Q --batch \
          --eval "(add-to-list 'load-path (expand-file-name \".\"))" \
          --eval "(require 'ellm)" \
          --eval "(require 'ellm-tests)" \
          --eval "(ert-run-tests-batch-and-exit)"